services:
  app:
    image: python:3.13-alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DYNACONF_SETTINGS=settings.toml
    command: >
      sh -c "pip install -r requirements.txt && python3 main.py"
    depends_on:
      - chrome
    networks:
      - mynetwork
    stdin_open: true
    tty: true

  chrome:
    image: seleniarm/standalone-chromium:124.0
    environment:
      - START_XVFB=false
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
